"""empty message

Revision ID: da10a0744947
Revises: 
Create Date: 2023-12-20 21:55:06.590517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da10a0744947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sap_stock')
    op.drop_table('stocks')
    op.drop_table('loan')
    op.drop_table('stock_model')
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('changed_on', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_by_fk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('changed_by_fk', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ab_user', ['changed_by_fk'], ['id'])
        batch_op.create_foreign_key(None, 'ab_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'ab_user', ['created_by_fk'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ab_user', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('changed_by_fk')
        batch_op.drop_column('created_by_fk')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('stock_id')
        batch_op.drop_column('stock_type')
        batch_op.drop_column('user_id')
        batch_op.drop_column('changed_on')
        batch_op.drop_column('created_on')

    op.create_table('stock_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('purchase_price', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('loan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('interest_rate', sa.FLOAT(), nullable=False),
    sa.Column('term', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('purchase_price', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('sap_stock',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('purchase_price', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###
